# Names of different land categories.
LCM2015_NAME = {0: 'Default',
                1: 'Broadleaved Woodland',
                2: 'Coniferous Woodland',
                3: 'Arable and Horticulture',
                4: 'Improved Grassland',
                5: 'Neutral Grassland',
                6: 'Calcareous Grassland',
                7: 'Acid Grassland',
                8: 'Fen, Marsh and Swamp',
                9: 'Heather',
                10: 'Heather Grassland',
                11: 'Bog',
                12: 'Inland Rock',
                13: 'Saltwater',
                14: 'Freshwater',
                15: 'Supra-littoral Rock',
                16: 'Supra-littoral Sediment',
                17: 'Littoral Rock',
                18: 'Littoral Sediment',
                19: 'Saltmarsh',
                20: 'Urban',
                21: 'Suburban'}


# RGB values for rendering different land categories.
LCM2015_COLORMAP = {0: [240, 240, 240],
                    1: [255, 0, 0],
                    2: [0, 102, 0],
                    3: [115, 38, 0],
                    4: [0, 255, 0],
                    5: [127, 229, 127],
                    6: [112, 168, 0],
                    7: [153, 129, 0],
                    8: [255, 255, 0],
                    9: [128, 26, 128],
                    10: [230, 140, 166],
                    11: [0, 128, 115],
                    12: [210, 210, 255],
                    13: [0, 0, 128],
                    14: [0, 0, 255],
                    15: [204, 179, 0],
                    16: [204, 179, 0],
                    17: [255, 255, 128],
                    18: [255, 255, 128],
                    19: [128, 128, 255],
                    20: [0, 0, 0],
                    21: [128, 128, 128]}

# Representative height for clutters located in different land categories, in meter.
LCM2015_CLUTTER_HEIGHT = {'Default': 0.0,
                          'Broadleaved Woodland': 15.0,
                          'Coniferous Woodland': 5.0,
                          'Arable and Horticulture': 2.0,
                          'Improved Grassland': 1.0,
                          'Neutral Grassland': 1.0,
                          'Calcareous Grassland': 1.0,
                          'Acid Grassland': 1.0,
                          'Fen, Marsh and Swamp': 2.0,
                          'Heather': 1.0,
                          'Heather Grassland': 2.0,
                          'Bog': 0.25,
                          'Inland Rock': 0.5,
                          'Saltwater': 0.0,
                          'Freshwater': 0.0,
                          'Supra-littoral Rock': 0.75,
                          'Supra-littoral Sediment': 0.25,
                          'Littoral Rock': 0.5,
                          'Littoral Sediment': 0.25,
                          'Saltmarsh': 0.0,
                          'Urban': 15.0,
                          'Suburban': 10.0}
